routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Curso\Estudiantes;

Route::get('/', function () {
    return view('estudiantes.crearEstudiante');
});

Route::resource('estudiantes', 'EstudiantesController');
Route::get('/crearEstudiante', 'EstudiantesController@create');

Route::resource('empleados', 'EmpleadosController');
Route::get('/crearEmpleado', 'EmpleadosController@create');

Route::resource('libros', 'LibrosController');
Route::get('/crearLibro', 'LibrosController@create');


Route::resource('prestamos', 'PrestamoController');
Route::get('/crearPrestamo', 'PrestamoController@create');

app/Empleados.php
<?php

namespace Sistema;

use Illuminate\Database\Eloquent\Model;

class Empleados extends Model
{
    protected $table = 'empleados';


    protected $fillable = [
        'nombre',
        'edad',
        'cedula',
        'sexo'
      ];
}

app/Http/Controllers/EmpleadosController.php
<?php

namespace Sistema\Http\Controllers;

use Sistema\Empleados;
use Illuminate\Http\Request;

class EmpleadosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $empleado = Empleados::all();
        

        return view('empleados.index', compact('empleado'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('empleados.crearEmpleado');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=>'required|string',
            'edad'=> 'required|integer:unsigned',
            'cedula'=>'required|integer',
            'sexo'=>'required|string',
            
          ]);
          $empleado = new Empleados([
            'nombre'=>$request->get('nombre'),
            'edad'=>$request->get('edad'),
            'cedula'=>$request->get('cedula'),
            'sexo'=>$request->get('sexo'),
            
            
          ]);
          $empleado->save();
          return redirect('/empleados')->with('success', 'Stock has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \Sistema\Empleados  $empleados
     * @return \Illuminate\Http\Response
     */
    public function show(Empleados $empleados)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Sistema\Empleados  $empleados
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $empleado = Empleados::find($id);
        return view('empleados.edit',compact('empleado'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Sistema\Empleados  $empleados
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $request->validate([
            'nombre'=>'required|string',
            'edad'=> 'required|integer:unsigned',
            'cedula'=>'required|integer',
            'sexo'=>'required|string',
            
          ]);
    
          $empleado = Empleados::find($id);
            $empleado->nombre = $request->get('nombre');
            $empleado->edad= $request->get('edad');
            $empleado->cedula= $request->get('cedula');
            $empleado->sexo= $request->get('sexo');
       
          $empleado->save();
    
          return redirect('/empleados')->with('success', 'Stock has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Sistema\Empleados  $empleados
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $empleado = Empleados::find($id);
        $empleado->delete();

        return redirect('/empleados')->with('success', 'Stock has been deleted Successfully');
    }
}

resources/views/empleados/crearEmpleado.blade.php
@extends('layouts.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Añadir empleado
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('empleados.store') }}">
          <div class="form-group">
              @csrf
              <label for="nombre">Nombre:</label>
              <input type="text" class="form-control" name="nombre"/>
          </div>
          <div class="form-group">
              <label for="edad">Edad: </label>
              <input type="number" class="form-control" name="edad"/>
          </div>
        <div class="form-group">
          <label for="cedula">Cedula :</label>
          <input type="number" class="form-control" name="cedula"/>
      </div>
      <div class="form-group">
        <label for="Sexo">Sexo :</label>
        <input type="radio" name="sexo" value="hombre" checked> Male
        <input type="radio" name="sexo" value="mujer"> Female<br>
    </div>
         
          <button type="submit" class="btn btn-primary">Añadir</button>
      </form>
  </div>
</div>
@endsection

resources/views/empleados/edit.blade.php
@extends('layouts.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('empleados.update', $empleado->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="nombre">Nombre:</label>
          <input type="text" class="form-control" name="nombre" value={{ $empleado->nombre }} />
        </div>
        <div class="form-group">
          <label for="edad">Edad :</label>
          <input type="number" class="form-control" name="edad" value={{ $empleado->edad }} />
        </div>
          <div class="form-group">
            <label for="cedula">Cedula :</label>
            <input type="number" class="form-control" name="cedula" value={{ $empleado->cedula }} />
          </div>
          <div class="form-group">
            <label for="Sexo">Sexo :</label>
            <input type="radio" name="sexo" value="hombre" checked> Male
            <input type="radio" name="sexo" value="mujer"> Female<br>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/empleados/index.blade.php
@extends('layouts.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nombre</td>
          <td>Edad</td>
          <td>Cedula</td>
          <td>Sexo</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($empleado as $em)
        <tr>
            <td>{{$em->id}}</td>
            <td>{{$em->nombre}}</td>
            <td>{{$em->edad}}</td>
            <td>{{$em->cedula}}</td>
            <td>{{$em->sexo}}</td>
            
            <td><a href="{{ route('empleados.edit',$em->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('empleados.destroy', $em->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection