routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Curso\Estudiantes;

Route::get('/', function () {
    return view('estudiantes.crearEstudiante');
});

Route::resource('estudiantes', 'EstudiantesController');
Route::get('/crearEstudiante', 'EstudiantesController@create');

Route::resource('empleados', 'EmpleadosController');
Route::get('/crearEmpleado', 'EmpleadosController@create');

Route::resource('libros', 'LibrosController');
Route::get('/crearLibro', 'LibrosController@create');


Route::resource('prestamos', 'PrestamoController');
Route::get('/crearPrestamo', 'PrestamoController@create');

app/Estudiantes.php
<?php

namespace Sistema;

use Illuminate\Database\Eloquent\Model;

class Estudiantes extends Model
{
    protected $table = 'estudiantes';


    protected $fillable = [
        'nombre',
        'edad',
        'carrera',
        'cedula',
        'sexo'
      ];
}

app/Http/Controllers/EstudiantesController.php
<?php

namespace Sistema\Http\Controllers;

use Sistema\estudiantes;
use Illuminate\Http\Request;

class EstudiantesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $estudiante = Estudiantes::all();
        

        return view('estudiantes.index', compact('estudiante'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('estudiantes.crearEstudiante');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=>'required|string',
            'edad'=> 'required|integer:unsigned',
            'carrera'=>'required|string',
            'cedula'=>'required|integer',
            'sexo'=>'required|string',
            
          ]);
          $estudiante = new Estudiantes([
            'nombre'=>$request->get('nombre'),
            'edad'=>$request->get('edad'),
            'carrera'=>$request->get('carrera'),
            'cedula'=>$request->get('cedula'),
            'sexo'=>$request->get('sexo'),
            
            
          ]);
          $estudiante->save();
          return redirect('/estudiantes')->with('success', 'Stock has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \Sistema\estudiantes  $estudiantes
     * @return \Illuminate\Http\Response
     */
    public function show(estudiantes $estudiantes)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Sistema\estudiantes  $estudiantes
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $estudiante = Estudiantes::find($id);
        return view('estudiantes.edit',compact('estudiante'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Sistema\estudiantes  $estudiantes
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
       
          $request->validate([
            'nombre'=>'required|string',
            'edad'=> 'required|integer:unsigned',
            'carrera'=>'required|string',
            'cedula'=>'required|integer',
            'sexo'=>'required|string',
            
          ]);
    
          $estudiante = Estudiantes::find($id);
            $estudiante->nombre = $request->get('nombre');
            $estudiante->edad= $request->get('edad');
            $estudiante->carrera= $request->get('carrera');
            $estudiante->cedula= $request->get('cedula');
            $estudiante->sexo= $request->get('sexo');
       
          $estudiante->save();
    
          return redirect('/estudiantes')->with('success', 'Stock has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Sistema\estudiantes  $estudiantes
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $estudiante = Estudiantes::find($id);
        $estudiante->delete();

        return redirect('/estudiantes')->with('success', 'Stock has been deleted Successfully');
    }
}

resources/views/estudiantes/crearEstudiante.blade.php
@extends('layouts.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Añadir estudiante
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('estudiantes.store') }}">
          <div class="form-group">
              @csrf
              <label for="nombre">Nombre:</label>
              <input type="text" class="form-control" name="nombre"/>
          </div>
          <div class="form-group">
              <label for="edad">Edad: </label>
              <input type="number" class="form-control" name="edad"/>
          </div>
          <div class="form-group">
            <label for="carrera">Carrera :</label>
            <input type="text" class="form-control" name="carrera"/>
        </div>
        <div class="form-group">
          <label for="cedula">Cedula :</label>
          <input type="number" class="form-control" name="cedula"/>
      </div>
      <div class="form-group">
        <label for="Sexo">Sexo :</label>
        <input type="radio" name="sexo" value="hombre" checked> Male
        <input type="radio" name="sexo" value="mujer"> Female<br>
    </div>
         
          <button type="submit" class="btn btn-primary">Añadir</button>
      </form>
  </div>
</div>
@endsection

resources/views/estudiantes/edit.blade.php
@extends('layouts.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('estudiantes.update', $estudiante->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
          <label for="nombre">Nombre:</label>
          <input type="text" class="form-control" name="nombre" value={{ $estudiante->nombre }} />
        </div>
        <div class="form-group">
          <label for="edad">Edad :</label>
          <input type="number" class="form-control" name="edad" value={{ $estudiante->edad }} />
        </div>
        <div class="form-group">
            <label for="carrera">Carrera :</label>
            <input type="text" class="form-control" name="carrera" value={{ $estudiante->carrera }} />
          </div>
          <div class="form-group">
            <label for="cedula">Cedula :</label>
            <input type="number" class="form-control" name="cedula" value={{ $estudiante->cedula }} />
          </div>
          <div class="form-group">
            <label for="Sexo">Sexo :</label>
            <input type="radio" name="sexo" value="hombre" checked> Male
            <input type="radio" name="sexo" value="mujer"> Female<br>
        </div>
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/estudiantes/index.blade.php
@extends('layouts.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nombre</td>
          <td>Edad</td>
          <td>Carrera</td>
          <td>Cedula</td>
          <td>Sexo</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($estudiante as $e)
        <tr>
            <td>{{$e->id}}</td>
            <td>{{$e->nombre}}</td>
            <td>{{$e->edad}}</td>
            <td>{{$e->carrera}}</td>
            <td>{{$e->cedula}}</td>
            <td>{{$e->sexo}}</td>
            
            <td><a href="{{ route('empleados.edit',$e->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('estudiantes.destroy', $e->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection