routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
use Curso\Estudiantes;

Route::get('/', function () {
    return view('estudiantes.crearEstudiante');
});

Route::resource('estudiantes', 'EstudiantesController');
Route::get('/crearEstudiante', 'EstudiantesController@create');

Route::resource('empleados', 'EmpleadosController');
Route::get('/crearEmpleado', 'EmpleadosController@create');

Route::resource('libros', 'LibrosController');
Route::get('/crearLibro', 'LibrosController@create');


Route::resource('prestamos', 'PrestamoController');
Route::get('/crearPrestamo', 'PrestamoController@create');

app/Libros.php
<?php

namespace Sistema;

use Illuminate\Database\Eloquent\Model;

class Libros extends Model
{
    protected $table = 'libros';


    protected $fillable = [
        'nombre',
        'editorial',
        'año',
        'ubicacion',
        'autor',
        'tipo',
        'area',
        'dias'
      ];

}

app/Http/Controllers/LibrosController.php
<?php

namespace Sistema\Http\Controllers;

use Sistema\Libros;
use Illuminate\Http\Request;

class LibrosController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $libro = Libros::all();
        

        return view('libros.index', compact('libro'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('libros.crearLibro');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'nombre'=>'required|string',
            'editorial'=> 'required|string',
            'año'=>'required|integer:unsigned',
            'ubicacion'=>'required|string',
            'autor'=>'required|string',
            'tipo'=>'required|string',
            'area'=>'required|string',
            'dias'=>'required|integer',
            
          ]);
          
          $libro = new Libros([
            'nombre'=>$request->get('nombre'),
            'editorial'=>$request->get('editorial'),
            'año'=>$request->get('año'),
            'ubicacion'=>$request->get('ubicacion'),
            'autor'=>$request->get('autor'),
            'tipo'=>$request->get('tipo'),
            'area'=>$request->get('area'),
            'dias'=>$request->get('dias'),

            
            
          ]);
          $libro->save();
          return redirect('/libros')->with('success', 'Stock has been added');
    }

    /**
     * Display the specified resource.
     *
     * @param  \Sistema\Libros  $libros
     * @return \Illuminate\Http\Response
     */
    public function show(Libros $libros)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \Sistema\Libros  $libros
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $libro = Libros::find($id);
        return view('libros.edit',compact('libro'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \Sistema\Libros  $libros
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request,$id)
    {
        $request->validate([
            'nombre'=>'required|string',
            'editorial'=> 'required|string',
            'año'=>'required|integer:unsigned',
            'ubicacion'=>'required|string',
            'autor'=>'required|string',
            'tipo'=>'required|string',
            'area'=>'required|string',
            'dias'=>'required|integer',
            
          ]);
    
          $libro = Libros::find($id);
          $libro->nombre= $request->get('nombre');
          $libro->editorial= $request->get('editorial');
          $libro->año=$request->get('año');
          $libro->ubicacion=$request->get('ubicacion');
          $libro->autor=$request->get('autor');
          $libro->tipo= $request->get('tipo');
          $libro->area=$request->get('area');
          $libro->dias=$request->get('dias');

          
          $libro->save();
    
          return redirect('/libros')->with('success', 'Stock has been updated');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \Sistema\Libros  $libros
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $libro = Libros::find($id);
        $libro->delete();

        return redirect('/libros')->with('success', 'Stock has been deleted Successfully');
    }
}

resources/views/libros/crearLibro.blade.php
@extends('layouts.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Añadir libro
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('libros.store') }}">
          <div class="form-group">
              @csrf
              <label for="nombre">Nombre:</label>
              <input type="text" class="form-control" name="nombre"/>
          </div>
          <div class="form-group">
              <label for="editorial">Editorial: </label>
              <input type="text" class="form-control" name="editorial"/>
          </div>
          <div class="form-group">
            <label for="año">Año: </label>
            <input type="number" class="form-control" name="año"/>
        </div>
        <div class="form-group">
            <label for="ubicacion">Ubicacion: </label>
            <input type="text" class="form-control" name="ubicacion"/>
        </div>
        <div class="form-group">
            <label for="autor">Autor: </label>
            <input type="text" class="form-control" name="autor"/>
        </div>
        <div class="form-group">
            <label for="tipo">Tipo :</label>
            <input type="radio" name="tipo" value="normal" checked> Normal
            <input type="radio" name="tipo" value="reserva"> Reserva<br>
        </div>
       <div class="form-group">
        <label for="area">Area de conocimiento :</label>
        <input type="text" class="form-control" name="area"/>
      </div>
      <div class="form-group">
        <label for="dias">Dias de prestamo :</label>
        <input type="number" class="form-control" name="dias"/>
      </div>
      
         
          <button type="submit" class="btn btn-primary">Añadir</button>
      </form>
  </div>
</div>
@endsection

resources/views/libros/edit.blade.php
@extends('layouts.layout')

@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="card uper">
  <div class="card-header">
    Edit Share
  </div>
  <div class="card-body">
    @if ($errors->any())
      <div class="alert alert-danger">
        <ul>
            @foreach ($errors->all() as $error)
              <li>{{ $error }}</li>
            @endforeach
        </ul>
      </div><br />
    @endif
      <form method="post" action="{{ route('libros.update', $libro->id) }}">
        @method('PATCH')
        @csrf
        <div class="form-group">
            <label for="nombre">Nombre:</label>
            <input type="text" class="form-control" name="nombre" value={{ $libro->nombre }} />
          </div>
          <div class="form-group">
            <label for="editorial">Editorial :</label>
            <input type="text" class="form-control" name="editorial" value={{ $libro->editorial }} />
          </div>
          <div class="form-group">
              <label for="año">Año :</label>
              <input type="number" class="form-control" name="año" value={{ $libro->año }} />
            </div>
            <div class="form-group">
              <label for="ubicacion">Ubicacion :</label>
              <input type="text" class="form-control" name="ubicacion" value={{ $libro->ubicacion }} />
            </div>
            <div class="form-group">
                <label for="autor">Autor :</label>
                <input type="text" class="form-control" name="autor" value={{ $libro->autor }} />
              </div>
            <div class="form-group">
                <label for="tipo">Tipo :</label>
                <input type="radio" name="tipo" value="normal" checked> Normal
                <input type="radio" name="tipo" value="reserva"> Reserva<br>
            </div>
            <div class="form-group">
                <label for="area">Area de conocimiento:</label>
                <input type="text" class="form-control" name="area" value={{ $libro->area }} />
              </div>
           <div class="form-group">
                <label for="dias">Dias de prestamo:</label>
                <input type="number" class="form-control" name="dias" value={{ $libro->dias }} />
              </div>  

    
        <button type="submit" class="btn btn-primary">Update</button>
      </form>
  </div>
</div>
@endsection

resources/views/libros/index.blade.php
@extends('layouts.layout')
@section('content')
<style>
  .uper {
    margin-top: 40px;
  }
</style>
<div class="uper">
  @if(session()->get('success'))
    <div class="alert alert-success">
      {{ session()->get('success') }}  
    </div><br />
  @endif
  <table class="table table-striped">
    <thead>
        <tr>
          <td>ID</td>
          <td>Nombre</td>
          <td>Editorial</td>
          <td>Año</td>
          <td>Ubicacion</td>
          <td>Autor</td>
          <td>Tipo</td>
          <td>Area de conocimiento</td>
          <td>Dias de prestamo</td>
          <td colspan="2">Action</td>
        </tr>
    </thead>
    <tbody>
        @foreach($libro as $l)
        <tr>
            <td>{{$l->id}}</td>
            <td>{{$l->nombre}}</td>
            <td>{{$l->editorial}}</td>
            <td>{{$l->año}}</td>
            <td>{{$l->ubicacion}}</td>
            <td>{{$l->autor}}</td>
            <td>{{$l->tipo}}</td>
            <td>{{$l->area}}</td>
            <td>{{$l->dias}}</td>
            
            
            <td><a href="{{ route('libros.edit',$l->id)}}" class="btn btn-primary">Edit</a></td>
            <td>
                <form action="{{ route('libros.destroy', $l->id)}}" method="post">
                  @csrf
                  @method('DELETE')
                  <button class="btn btn-danger" type="submit">Delete</button>
                </form>
            </td>
        </tr>
        @endforeach
    </tbody>
  </table>
<div>
@endsection